### PR TITLE
Scrub MCWS user ID of invalid namespace characters

### LINKED ISSUE #387: MCWS Identity provider doesn't scrub user id of invalid characters.
**Describe the defect**

In the [MCWS identity provider](https://github.com/NASA-AMMOS/openmct-mcws/blob/main/src/services/identity/createMCWSUser.js) the user.id and user.name constructor are both set to the same value. This is due to the default MCWS identity return only including one such entry: 
`[{"subject": "current_user", "predicate": "has_userid", "object": "user_id"}, {"subject": "nfs_information_provider", "predicate": "has_registered_namespace", "object": "/my/mio/location"}]`

The issue occurs if your CAM is set to return the fully qualified name of a user from LDAP instead of just the username. e.g. UserLastName, UserFirstName (usergroup). non-standard characters, such as commas and parentheses break namespace paths once the information object is created. 

**Expected behavior**

I would expect that the user.id field is scrubbed of characters that aren't valid for namespaces, instead of assuming that the return from MCWS will always be a valid namespace path. 

This can be accomplished with the following change: 

`
constructor(name) {
      super(name, name); // no id is returned, so we use name twice
    }
`
becomes

`
constructor(name) {
      super(name.replace(/[^a-zA-Z0-9]/g, ''), '', name); // no id is returned, so we use name twice
    }
`

**Steps To Reproduce**
1. Configure your identity provider for MCWS to return more than just the username. 
2. Load OMM
3. Attempt to create an object and observe that the namespace of the object inherits non-ascii characters (and thus will not work)

**Additional context**

This bug was discovered due to using full usernames as the identity return for a cleaner folder look. 

crit4

### PR DESCRIPTION
**Pull request by jvigliotta**
Fixes: https://github.com/NASA-AMMOS/openmct-mcws/issues/387 in v5.3.2. 

This can't be tested with development storage, so you'll need something to emulate the MCWS persistence storage, as well as send a poorly-formatted name. 

1. clone https://github.jpl.nasa.gov/IEMS/iems-gds-fast-mcws-persistence
3. cd into iems-gds-fast-mcws-persistence
4. edit the following file: fastmio/fastMIOServer.py line 165
5. replace remote_user='unknown' with remote_user='Unknown, User (999A)'
6. edit the following file: fastmio/config/fastmio.cfg
Line 26: 
`import_mcws_namespaces = true -> import_mcws_namespaces = false`
Line 40: 
`import_fastmio_namespaces=false -> import_fastmio_namespaces=true`

Lines 44-48: 

>ns_map= {
>        "/shared":"/home/user/shared",
>        "/systems":"/home/user/systems",
>        "/users":"/home/user/users"
>        }

becomes

>ns_map= {
>        "/shared":"/your/path/here/shared",
>        "/users":"/your/path/here/users"
>        }

7. Create a python3 virtual environment and install fastmio's required packeges. 

>python3 -m venv fastmioenv
>source fastmioenv/bin/activate
>pip install -e .

Fastmio is now configured to send your development server a MCWS namespace with an invalid ID. 

Run fast mio with python fastmio/fastMIOServer.py and leave the terminal up for your testing purposes. 

Note that you may need to delete the contents of <path to your local test users dir> while you test - fastmio will automatically pick up any changes to the and does not need to be restarted if you do. 

Next, configure the webpack dev environment and config.js to use the fastmio environment you just set up.  

Webpack dev: 
set your API_URL environment variable to localhost:8093 

config.js 

1. set the mcwsUrl to: 
`mcwsUrl: 'http://localhost:8093/mcws',`
2. Set the URLs for the development namespaces like so: 
3.  
>namespaces: [
>      {
>        key: 'r50-dev',
>        name: 'R5.0 Shared',
>        url: '/fastmio/shared'
>      },
>      {
>        userNamespace: true,
>        key: 'r50-dev',
>        name: 'R5.0 Users',
>        url: '/fastmio/users'
>      }
>    ],

uncomment the proxyUrl line, but do not uncomment the useDeveloperStorage line, as we're going to use fastmio in this scenario as our test storage provider. Don't forget to remove the comma after useDeveloperStorage if it is now the last item in the config file. 

running npm start should now run MCT as a developer server but with fastmio providing a fully qualified mcws-like name, allowing this functionality to be tested .

Verify that the user folder is automatically created with the full user name and that the logged in user in the MCT status bar is the correct user name. 
Verify that if you create an object in the user's folder, the namespace and location parameters do not contain spaces, commas, or other invalid characters. 
Verify that you can create objects in the shared folder with no issues as well.

### CODE REVIEW

**Review by davetsay — CHANGES_REQUESTED** [review]
I'd like `interpolateUsername` and `createIfMissing` to follow the same arg order, id then name. I believe they are both internal functions so it shouldn't affect users.

Would like to examine the different user returns we could be getting. ie. CAM, LDAP, or, at least those two.

SonarCould analysis should be addressed if possible.

**Review by davetsay — APPROVED** [review]
i had left a comment about param order. i think its a good idea but approving

File: src/persistence/utils.js [hunk 1]
```diff
@@ -65,18 +65,20 @@ export function createNamespace(namespace) {
...
  *
  * @private
  * @param {NamespaceTemplate} templateObject namespace template object.
- * @param {string} username a username.
+ * @param {string} userId the user ID
+ * @param {string} username the username (default is userId)
  * @returns {NamespaceDefinition} a namespace definition object.
  */
-export function interpolateUsername(templateObject, username) {
+export function interpolateUsername(templateObject, userId, username = userId) {
```
Comment (davetsay) [inline src/persistence/utils.js:77]: 👍
