### PR TITLE
[Persistence] Removes required user namespace and inability to manipulate older objects

### LINKED ISSUE #55: [DEFECT] OMM 5.0 requires at least one usernamespace to have userNamespace:true
part of https://jira.jpl.nasa.gov/browse/OMM-177

**Describe the defect**
There is some logic that is breaking if an instance is configured without a namespace with `containsNamespaces=true`.

**Expected behavior**
You should be able to have a setup that doesn't have user namepspaces.

**Steps To Reproduce**
1. Configure OMM without a namespace with `containsNamespaces=true`

**Additional context**
Add any other context, code snippets, error messages, screen shots about the problem here.

|Criticality|Name|Description|
|---|---|---|
|crit1|Critical|Defect makes the software unusable for mission operations.|
|crit2|Major|Defect has significant impact on usability of delivered software for mission operations. User experience is difficult and/or cumbersome. Workaround available is arduous.|
|crit3|Moderate|Defect has moderate to mild impact on usability of delivered software for mission operations. User experience is degraded but workable.|
|crit4|Minor|Defect means software does not work as originally intended, but the defect has little impact on the usability of the delivered software.|

### LINKED ISSUE #59: [DEFECT] Can't delete objects created in older versions of OMM (Investigate)
part of https://jira.jpl.nasa.gov/browse/OMM-177

**Describe the defect**
Objects in folders created before 5.0 can't seem to be modified by 5.0, specifically for removing objects.

**Expected behavior**
You should be able to remove objects in older version persistences.

**Steps To Reproduce**
1. Install 5.0 on top of an older persistence storage
2. Try to remove an old object

### PR DESCRIPTION
**Pull request by jvigliotta**
closes #55 
closes #59

This fix makes it so you can have an instance of OMM that doesn't have a user namespace configured. This also fixes an issue where you were unable to delete older instance objects (pre 5.0) due to mismatching composition formats.

### CODE REVIEW

File: src/persistence/existingNamespaceUpdateInterceptor.js [hunk 1]
```diff
@@ -6,11 +6,36 @@ export default function existingNamespaceUpdateInterceptor(openmct, usersNamespa
             return shouldCheck;
         },
         invoke: (identifier, object) => {
+            // check for old user namespace style
```
Comment (davetsay) [inline src/persistence/existingNamespaceUpdateInterceptor.js:9]: 👍

File: src/persistence/existingNamespaceUpdateInterceptor.js [hunk 2]
```diff
@@ -6,11 +6,36 @@ export default function existingNamespaceUpdateInterceptor(openmct, usersNamespa
...
             if (object.location === usersNamespace.key) {
                 object.location = usersNamespace.id;
                 openmct.objects.mutate(object, 'location', usersNamespace.id);
             }
 
+            // check for old composition style
```
Comment (davetsay) [inline src/persistence/existingNamespaceUpdateInterceptor.js:15]: 👍

File: src/persistence/existingNamespaceUpdateInterceptor.js [hunk 3]
```diff
@@ -6,11 +6,36 @@ export default function existingNamespaceUpdateInterceptor(openmct, usersNamespa
...
+            if (object.composition?.length) {
+                let updatedComposition = false;
+
+                object.composition = object.composition.map((keystring) => {
+                    if (typeof keystring === 'string') {
+                        updatedComposition = true;
+
+                        const parts = keystring.split(':', 2);
```
Comment (davetsay) [inline src/persistence/existingNamespaceUpdateInterceptor.js:23]: i think this could unintentionally throw away part of the string in the case of dictionary items, aka `namespace='vista'` items. Would `openmct.parseKeyString` work here?

File: src/persistence/existingNamespaceUpdateInterceptor.js [hunk 4]
```diff
@@ -6,11 +6,36 @@ export default function existingNamespaceUpdateInterceptor(openmct, usersNamespa
...
                 openmct.objects.mutate(object, 'location', usersNamespace.id);
             }
 
+            // check for old composition style
+            if (object.composition?.length) {
+                let updatedComposition = false;
+
+                object.composition = object.composition.map((keystring) => {
+                    if (typeof keystring === 'string') {
+                        updatedComposition = true;
```
Comment (davetsay) [inline src/persistence/existingNamespaceUpdateInterceptor.js:21]: Side effect in a map!?! You savage.

I'll allow it.

File: src/persistence/plugin.js [hunk 5]
```diff
@@ -13,8 +13,12 @@ export default function MCWSPersistenceProviderPlugin(configNamespaces) {
         const mcwsPersistenceProvider = new MCWSPersistenceProvider(openmct, namespaces);
 
         const usersNamespace = namespaces.find((namespace) => namespace.containsNamespaces);
-        const checkOldNamespaces = localStorage.getItem(`r5.0_old_namespace_checked:${usersNamespace.key}`) === null;
-        existingNamespaceUpdateInterceptor(openmct, usersNamespace, checkOldNamespaces);
+
```
Comment (davetsay) [inline src/persistence/plugin.js:16]: 👍

**Review by davetsay — CHANGES_REQUESTED** [review]
one quick change

File: src/persistence/existingNamespaceUpdateInterceptor.js (hunk 4 above)
Comment (jvigliotta) [reply src/persistence/existingNamespaceUpdateInterceptor.js:21]: ha, I didn't even think about that... next time.

File: src/persistence/existingNamespaceUpdateInterceptor.js (hunk 3 above)
Comment (jvigliotta) [reply src/persistence/existingNamespaceUpdateInterceptor.js:23]: nail on the head my friend... will update

**Review by davetsay — APPROVED** [review]
looks good
