### PR TITLE
Fix `net::ERR_INSUFFICIENT_RESOURCES` errors on HTTP2 introduced in 5.4.0

### LINKED ISSUE #373: Fix large amount of network requests on load dropping some requests
**Describe the sustaining activity**

Changes in v5.4.1 are good multi-mission changes and should be brought into main code path.

Changes:
- https://github.com/NASA-AMMOS/openmct-mcws/issues/368

**Expected behavior**

**Testing Instructions**
1. Should be covered by any tests created for the patch release or regression testing.

**Additional context**

### PR DESCRIPTION
**Pull request by jvigliotta**
fixes: #373 

Main fix here is the removal of `keapalive = true` for fetch options. This was introduced to increase load times and testing seemed to indicate it did, though now it's believed that was a false positive. This flag will crush Open MCT using the MCWS Adapter plugin on large quantities of requests. The fix is to remove. We'll do testing to ensure load times aren't affected. Additional fixes for race conditions introduced in trying to fix the underlying issue are included as well as they are good changes.

### CODE REVIEW

File: src/persistence/BaseMCWSPersistenceProvider.js [hunk 1]
```diff
@@ -59,15 +59,25 @@ export default class BaseMCWSPersistenceProvider {
    * @returns {Promise.<NamespaceDefinition[]>} persistenceNamespaces
    */
   async getPersistenceNamespaces() {
```
Comment (davetsay) [inline src/persistence/BaseMCWSPersistenceProvider.js:61]:
```suggestion
async getPersistenceNamespaces() {
    if (!this.persistenceNamespaces) {
      this.persistenceNamespaces = (async () => {
        const rootNamespaces = await this.getRootNamespaces();
        const allContainedNamespaces = await this.getAllContainedNamespaces(rootNamespaces);

        const persistenceNamespaces = [...rootNamespaces, ...allContainedNamespaces];

        return persistenceNamespaces;
      })();
    }

    return this.persistenceNamespaces;
}
```

**Review by davetsay — APPROVED** [review]

File: src/persistence/BaseMCWSPersistenceProvider.js (hunk 1 above)
Comment (jvigliotta) [reply src/persistence/BaseMCWSPersistenceProvider.js:61]: I'm going to keep it  as it is because `this.persistenceNamespaces` stays a real array after load or `undefined` if there's an error, which matches it's  name and the JSDoc.  Your suggestions is functionally equivalent, but I think the current way is a bit more clear and creates a solid separation between the promise and the actual namespaces array.
