### PR TITLE
392 force uppercase module subscriptions

### LINKED ISSUE #392: EVR streams by module can have mismatched case on the module subscription
**Describe the defect**

When OMM subscribes to an evr stream by module, the code checks the module from the EVR dictionary and pegs it to lowercase: 
domainObject.telemetry.definition.module.toLowerCase();

This *appears* to be to ensure that subsequent subscriptions to MCWS' EVR stream endpoint are lowercase. However, MCWS's AbstractStreamEndpointAdapter _already_ converts all filters to lowercase, which means this conversion isn't needed on OMM's end - and indeed it's not used for either channels or evrs by level in OMM. 

Due to OMM converting the module to lowercase, there's a mismatch on the key of the returned evr data. 

Example: 
module = TEST
omm internal subscription: test
request to mcws filter: module=test
subscribers[test]
key: TEST

This is the behavior that breaks subscriptions on the top level EVR object and EVR queries by module or name. 

**Expected behavior**

EVR module subscriptions should be always all caps. This is consistent with both historical queries and other EVR filters. I tested this against NISAR MCWS realtime and verified that all caps module subscriptions are identical to all lowercase module subscriptions. 

**Steps To Reproduce**
1. Use any EVR module where the module in AMPCS is in all caps. 

**Additional context**

### PR DESCRIPTION
**Pull request by jvigliotta**
Fixes: https://github.com/NASA-AMMOS/openmct-mcws/issues/392

1. Corrects order of operations in assigning a module to an EVR stream request. 

Before: 
domainObject.telemetry.definition.module first
domainObject.telemetry.evr_name.split("_")[0] if evr_name existed
domainObject.telemetry.module third

This caused it to break if modules had an underscore in them, and would also cause it to default to the legacy EVR name method before using the module definition from the dictionary. 

Now: 
domainObject.telemetry.definition.module first
domainObject.telemetry.module second
domainObject.telemetry.evr_name.split("_")[0] as a last ditch resort. 

This should work for cases where the module has underscores now, as the module provided by the EVR dictionary will be used in all cases before trying to assume a module from the evr name. 

2. Makes module stream requests all caps and all internally consistent. 
There were instances where an EVR return would have an all caps module name, but OMM was forcing all lowercase module names in the evr stream. This caused a disconnect with the MCWS return so no EVRs would appear in module streams. 

MCWS is case-agnostic for EVR streams, so best method here is to make stream requests internally consistent - other filters use all caps already (well, they use the dictionary default which is all caps), so we should also use it for both the request and the key.

### CODE REVIEW

File: src/realtime/MCWSEVRStreamProvider.js [hunk 1]
```diff
@@ -32,19 +32,28 @@ class MCWSEVRStreamProvider extends MCWSStreamProvider {
...
       domainObject.telemetry.definition &&
       domainObject.telemetry.definition.module &&
-      domainObject.telemetry.definition.module.toLowerCase();
+      domainObject.telemetry.definition.module.toUpperCase();
+
+      // This is the top-level vista.evrModule object, which contains 
+      // A module definition but not in the definition object.  
+      // This must be captured before an attempt at legacy EVRs is made
+      // in case the module has underscores in it. 
+      if (!module || module.length <= 0) {
```
Comment (jvigliotta) [inline src/realtime/MCWSEVRStreamProvider.js]: I think you can simplify (this was messy before you) the whole first part of this method with optional chaining:

```js
let module = domainObject?.telemetry?.definition?.module?.toUpperCase();

// This is the top-level vista.evrModule object, which contains
// a module definition but not in the definition object.
// This must be captured before attempting legacy EVRs,
// in case the module contains underscores.
if (!module?.length) {
    module = domainObject?.telemetry?.module?.toUpperCase();
}
```

File: src/realtime/MCWSEVRStreamProvider.js [hunk 2]
```diff
@@ -32,19 +32,28 @@ class MCWSEVRStreamProvider extends MCWSStreamProvider {
...
+          module = domainObject.telemetry
+              && domainObject.telemetry.module
+              && domainObject.telemetry.module.toUpperCase();
+      }
 
     // legacy inference of module by evr_name
-    // if this fallback is used will break on module names containing underscores
+    // This should *never* occur with modern telemetry dictionaries.
     if (!module || module.length <= 0) {
```
Comment (jvigliotta) [inline src/realtime/MCWSEVRStreamProvider.js:52]: I think we can clean this section up as well, similarly:

```js
if (!module?.length) {
    console.warn('Legacy domain objects should not be used anymore!');
    const evrName = domainObject?.telemetry?.evr_name;
    module = evrName?.split('_')?.[0]?.toUpperCase();
}
```

Also, throw some optionally chaining in the assignment as a precaution.

Comment (davetsay) [reply src/realtime/MCWSEVRStreamProvider.js:52]: We don't want `undefined` modules, so we are screwed if use optional chaining or not at this point anyways.

**Review by davetsay — CHANGES_REQUESTED** [review]
I think this needs comments or documentation or something. a link to mcws documentation would be nice, but not sure we can do that if mcws documentation is not yet open sourced.

File: src/realtime/MCWSEVRStreamProvider.js (hunk 2 above)
Comment (jvigliotta) [reply src/realtime/MCWSEVRStreamProvider.js:52]: yeah but it just LOOKS great

**Comment by jvigliotta** [comment]
> I think this needs comments or documentation or something. a link to mcws documentation would be nice, but not sure we can do that if mcws documentation is not yet open sourced.

I was looking through the docs to see if there was anything in particular I could pull, I wasn't finding anything. Is there anything in particular you'd like me to pull from there? I looked at the user guide and product guide

**Comment by davetsay** [comment]
> > I think this needs comments or documentation or something. a link to mcws documentation would be nice, but not sure we can do that if mcws documentation is not yet open sourced.
> 
> I was looking through the docs to see if there was anything in particular I could pull, I wasn't finding anything. Is there anything in particular you'd like me to pull from there? I looked at the user guide and product guide

The comment i'm referring to is why we are doing all this uppercase nonsense. It may not be in MCWS. It is just what AMPCS does. This comes from the discussion about formatting we had with @mudinthewater regarding what MCWS responses give us and what it expects for filters in requests, and why we ended up with uppercase, instead of lowercase. Unless we have the context of why we cannot change from uppercasing everything, we could very likely forget it and change this behavior in the future.

**Comment by davetsay** [comment]
> > > I think this needs comments or documentation or something. a link to mcws documentation would be nice, but not sure we can do that if mcws documentation is not yet open sourced.
> > 
> > 
> > I was looking through the docs to see if there was anything in particular I could pull, I wasn't finding anything. Is there anything in particular you'd like me to pull from there? I looked at the user guide and product guide
> 
> The comment i'm referring to is why we are doing all this uppercase nonsense. It may not be in MCWS. It is just what AMPCS does. This comes from the discussion about formatting we had with @mudinthewater regarding what MCWS responses give us and what it expects for filters in requests, and why we ended up with uppercase, instead of lowercase. Unless we have the context of why we cannot change from uppercasing everything, we could very likely forget it and change this behavior in the future.

add the comment to the relevant files

**Review by davetsay — APPROVED** [review]
