### PR TITLE
[Unit Tests] Update unit tests

### LINKED ISSUE #259: Update Unit Tests broken from updates
**Description**

Fix the following unit tests:
- MCWSNamespaceModelProviderSpec.js
- MCWSNamespaceServiceSpec.js
- MCWSPersistenceProviderSpec.js
- DataProductRowSpec.js
- VenueSpec.js

Issues Created for any remaining unit test issues at this point:
- https://github.com/NASA-AMMOS/openmct-mcws/issues/257
- https://github.com/NASA-AMMOS/openmct-mcws/issues/258

**Additional context**

### PR DESCRIPTION
**Pull request by jvigliotta**
closes #259

Updates unit tests broken during updates/upgrades.

### CODE REVIEW

File: src/persistence/test/MCWSNamespaceServiceSpec.js [hunk 1]
```diff
@@ -1,382 +1,356 @@
...
-                    ammosDefinition
-                ];
-
-                namespaceService = new MCWSNamespaceService(
-                    mockOpenmct,
-                    $window,
-                    filterDefinitions
-                );
+    // need to fix this (issue is mocking window.location.pathname)
+    xdescribe('namespace filtering', () => {
```
Comment (davetsay) [inline src/persistence/test/MCWSNamespaceServiceSpec.js:284]: is the `xdescribe` intended?

File: src/persistence/test/MCWSNamespaceModelProviderSpec.js [hunk 2]
```diff
@@ -1,138 +1,246 @@
...
-    // MCWSNamespaceModelProvider
-) {
-    'use strict';
-
-    xdescribe('MCWSNamespaceModelProvider', function () {
-        var namespaceService,
+
+import MCWSUserContainerProvider from '../MCWSUserContainerProvider';
+import MCWSPersistenceProvider from '../MCWSPersistenceProvider';
+import mcws from '../../services/mcws/mcws';
```
Comment (davetsay) [inline src/persistence/test/MCWSNamespaceModelProviderSpec.js:4]: you can use the defined path `'services/mcws/mcws'`

File: src/persistence/test/MCWSNamespaceServiceSpec.js [hunk 3]
```diff
@@ -1,382 +1,356 @@
...
-
-        beforeEach(function () {
-            $window = {
-                location: {
-                    pathname: '/mcws/clients/vista/'
-                }
-            };
+import MCWSPersistenceProvider from '../MCWSPersistenceProvider';
+import MCWSUserContainerProvider from '../MCWSUserContainerProvider';
+import mcws from '../../services/mcws/mcws';
```
Comment (davetsay) [inline src/persistence/test/MCWSNamespaceServiceSpec.js:3]: you can use the defined path `'services/mcws/mcws'`

File: src/persistence/test/MCWSPersistenceProviderSpec.js [hunk 4]
```diff
@@ -1,189 +1,186 @@
...
-
-        it("provides a promise for available spaces", function (done) {
-            persistence.listSpaces()
-                .then(function (spaces) {
-                    expect(spaces).toEqual(['testSpace', 'testSpace2']);
-                    done();
-                })
-        });
+import MCWSPersistenceProvider from '../MCWSPersistenceProvider';
+import mcws from '../../services/mcws/mcws';
```
Comment (davetsay) [inline src/persistence/test/MCWSPersistenceProviderSpec.js:2]: you can use the defined path `'services/mcws/mcws'`

File: src/persistence/test/MCWSPersistenceProviderSpec.js [hunk 5]
```diff
@@ -1,189 +1,186 @@
...
-                });
-        });
+    it('provides a promise for available namespaces', async (done) => {
+        const spaces = await mcwsPersistenceProvider.getPersistenceNamespaces();
+        expect(spaces).toEqual(persistenceNamespaces);
+        done();
+    });
+    
+    // DO WE DELETE THIS TEST? I don't think we use this functionality anymore.
+    xit('provides a listing of namespaces when provided a namespace definition', async (done) => {
```
Comment (davetsay) [inline src/persistence/test/MCWSPersistenceProviderSpec.js:66]: we do call `getNamespacesFromMCWS` so maybe this is still an okay unit test

File: src/persistence/test/MCWSPersistenceProviderSpec.js [hunk 6]
```diff
@@ -1,189 +1,186 @@
...
+            namespace: 'testSpace'
+        };
+        const model = {
+            someKey: 'some value'
+        };
+        const domainObject = {
+            identifier,
+            ...model
+        };
+        mockOpaqueFile.read.and.returnValue(Promise.resolve({json: () => Promise.resolve(model)}));
```
Comment (davetsay) [inline src/persistence/test/MCWSPersistenceProviderSpec.js:132]: i don't think we have models anymore without legacy domain objects?

File: src/services/session/test/controllers/SessionIndicatorControllerSpec.js [hunk 7]
```diff
@@ -1,189 +1,180 @@
...
-], function (
-    // SessionIndicatorController
-) {
-    'use strict';
-
-    xdescribe('SessionIndicatorController', function () {
-        var $scope,
+// import SessionIndicatorController from '../SessionIndicatorController';
+
+// this would be better tested in an e2e test
```
Comment (davetsay) [inline src/services/session/test/controllers/SessionIndicatorControllerSpec.js:3]: do these not work? it would be good to have some tests until we get e2e tests

File: src/services/session/test/controllers/SessionSelectorControllerSpec.js [hunk 8]
```diff
@@ -1,281 +1,270 @@
-/*global define,describe,beforeEach,jasmine,Promise,it,expect,afterEach,
-    waitsFor,runs*/
+// import SessionSelectorController from '../SessionSelectorController';
+
+// this would be better tested in an e2e test
```
Comment (davetsay) [inline src/services/session/test/controllers/SessionSelectorControllerSpec.js:3]: do these not work? it would be good to have some tests until we get e2e tests

**Review by davetsay — CHANGES_REQUESTED** [review]
Thanks for doing this. I have a couple comments inline.

Did all the other tests pass? I thought for sure the data product cell tests broke as a result of vue upgrade. Did we fix those elsewhere?

File: src/persistence/test/MCWSPersistenceProviderSpec.js (hunk 6 above)
Comment (jvigliotta) [reply src/persistence/test/MCWSPersistenceProviderSpec.js:132]: We basically store only models in MCWS, we strip out the identifier (similar to how do it in couchdb). So, when we retrieve the item from MCWS we use the key to get the model and we know the namespace, so we build the identifier in the provider before returning it to open mct.

File: src/persistence/test/MCWSPersistenceProviderSpec.js (hunk 5 above)
Comment (jvigliotta) [reply src/persistence/test/MCWSPersistenceProviderSpec.js:66]: I'll take a look.

File: src/persistence/test/MCWSNamespaceServiceSpec.js (hunk 1 above)
Comment (jvigliotta) [reply src/persistence/test/MCWSNamespaceServiceSpec.js:284]: I was stuck on this one. Open to suggestions, basically we check window.location.pathname and I'm not sure how to mock that to provide the paths we need for filtering. Previously it was angular and we'd pass in a mocked `$window` object.

**Comment by jvigliotta** [comment]
> Thanks for doing this. I have a couple comments inline.
> 
> Did all the other tests pass? I thought for sure the data product cell tests broke as a result of vue upgrade. Did we fix those elsewhere?

I'll look... I thought that was one of the first one's I did.

File: src/services/session/test/controllers/SessionIndicatorControllerSpec.js (hunk 7 above)
Comment (jvigliotta) [reply src/services/session/test/controllers/SessionIndicatorControllerSpec.js:3]: these are Vue component tests, so I think e2e is the better way to go.

File: src/services/session/test/controllers/SessionSelectorControllerSpec.js (hunk 8 above)
Comment (jvigliotta) [reply src/services/session/test/controllers/SessionSelectorControllerSpec.js:3]: these are Vue component tests, so I think e2e is the better way to go.

Comment (davetsay) [reply src/services/session/test/controllers/SessionSelectorControllerSpec.js:3]: I agree. But we don't have e2e tests yet. I think we should at least create an issue for these if we can't fix them now.

File: src/services/session/test/controllers/SessionIndicatorControllerSpec.js (hunk 7 above)
Comment (davetsay) [reply src/services/session/test/controllers/SessionIndicatorControllerSpec.js:3]: I agree. But we don't have e2e tests yet. I think we should at least create an issue for these if we can't fix them now.

File: src/persistence/test/MCWSNamespaceServiceSpec.js (hunk 1 above)
Comment (davetsay) [reply src/persistence/test/MCWSNamespaceServiceSpec.js:284]: lets create an issue to track this

**Review by davetsay — APPROVED** [review]
Please link to an issue. Also, create issues to back fill the tests that were x-ed out, the window mocking one and the vue components ones. We should still retain the same unit test coverage and deprecate only when we get e2e test coverage.
