### PR TITLE
[Persistence] Fix "missing" empty user folders from older persistence

### LINKED ISSUE #68: [DEFECT] OMM 5.0 doesn't create root (container) objects on-load
https://jira.jpl.nasa.gov/browse/OMM-174

**Describe the defect**
If no root objects are in a namespace, 5.0 won’t create them. If seeded with what a root container should look like, the folders load normally.

**Expected behavior**
A correctly mapped Open MCT without additional backend configuration should create and load folders.

**Steps To Reproduce**
1. 
2. 
3. 
4. 

**Environment (please complete the following information):**
 - Version []
 - Browser []

**Additional context**
Add any other context, code snippets, error messages, screen shots about the problem here.

|Criticality|Name|Description|
|---|---|---|
|crit1|Critical|Defect makes the software unusable for mission operations.|
|crit2|Major|Defect has significant impact on usability of delivered software for mission operations. User experience is difficult and/or cumbersome. Workaround available is arduous.|
|crit3|Moderate|Defect has moderate to mild impact on usability of delivered software for mission operations. User experience is degraded but workable.|
|crit4|Minor|Defect means software does not work as originally intended, but the defect has little impact on the usability of the delivered software.|

### PR DESCRIPTION
**Pull request by jvigliotta**
closes #68 

Pre 5.0, OMM would create user folders without a root object inside. Once we upgraded out of legacy persistence, these objects are created when the user folder is created. In older persistence, it would not know to create the new roots in an empty folder, this fix addresses this. It will be run once per user folder and will never run again after the folder root is created, due to a flag in localStorage. Deleting this flag, will cause the checks to run again (once).

### CODE REVIEW

File: src/persistence/MCWSPersistenceProvider.js [hunk 1]
```diff
@@ -1,5 +1,5 @@
 import mcws from '../services/mcws/mcws';
-import { createModelFromNamespaceDefinition, createIdentifierFromNamespaceDefinition } from './utils';
+import { createModelFromNamespaceDefinition, createIdentifierFromNamespaceDefinition, interpolateUsername } from './utils';
```
Comment (davetsay) [inline src/persistence/MCWSPersistenceProvider.js:2]:
```suggestion
import {
  createModelFromNamespaceDefinition,
  createIdentifierFromNamespaceDefinition,
  interpolateUsername
} from './utils';
```

File: src/persistence/missingUserFolderInterceptor.js [hunk 2]
```diff
@@ -0,0 +1,22 @@
+import { createModelFromNamespaceDefinition, interpolateUsername } from './utils';
```
Comment (davetsay) [inline src/persistence/missingUserFolderInterceptor.js:1]:
```suggestion
import {
  createModelFromNamespaceDefinition,
  interpolateUsername
} from './utils';
```

**Review by davetsay — CHANGES_REQUESTED** [review]
one small formatting change and we're good to go

**Review by davetsay — APPROVED** [review]
Nice work
