### PR TITLE
Account for network errors during user folder retrieval

### LINKED ISSUE #240: 5.3 user root persistence migration can indadvertantly delete user roots
**Describe the defect**

Despite receiving an http:200 on the /user/<username>/root object for 6 users, 5.3 initiated new object PUT requests overwriting the user persistence storage. 

**Expected behavior**

Not do that

**Steps To Reproduce**
- with OMM up and the individual user folders closed, in the network tab under "throttling" select "offline"
- keep the network tab open (clear if you want to better see requests)
- then open a user folder
- note there is a NETWORK error for the user folder request
- also note, right after that, there is a PUT request to "create" the user folder
- when this is fixed, there will be NO PUT request

This can cause issues with spotty network connections, where one connection may fail but another succeed - i.e. if download was briefly interrupted but upload wasn't, OMM could wipe the entire user folder list, which is what we've seen in logs. 

**Additional context**

crit4 - Now that we know the cause I've coded FastMIO to 409 conflict on these create requests if they already exist. This should provide plenty of time for the bug to be addressed in the next release cycle. Should verify that MCWS also 409 conflicts, otherwise this could be a 2.

### PR DESCRIPTION
**Pull request by jvigliotta**
closes #240 

If there's an error getting an object that is NOT a `404`, then we return an error object, similar to how we return a missing object for missing... objects (in our case for user folders a `404` means we create the root object: https://github.com/NASA-AMMOS/openmct-mcws/blob/3f58be75b257bc6c1ce2f31d1feb06b6f735ccda/src/persistence/BaseMCWSPersistenceProvider.js#L178
This addition of returning the error object, allows us to not try to save a missing object caused from a network error (no internet for example) in the case it's from an older persistence store that had folders on the backend, but no root object : https://github.com/NASA-AMMOS/openmct-mcws/blob/3f58be75b257bc6c1ce2f31d1feb06b6f735ccda/src/persistence/oldPersistenceFolderInterceptor.js#L52

Also added a retry loop. It will retry 3 times to get the object in 2, 4 and 8 second intervals at which point it will return the error object if there is still a network error.

### CODE REVIEW

File: src/persistence/MCWSPersistenceProvider.js [hunk 1]
```diff
@@ -29,6 +29,15 @@ export default class MCWSPersistenceProvider extends BaseMCWSPersistenceProvider
     } catch (error) {
       console.warn('MCWSPersistenceProvider:get', error);
 
+      // it's a network error, we don't want to create a new object
+      if (error.status !== 404) {
+        return {
```
Comment (davetsay) [inline src/persistence/MCWSPersistenceProvider.js:34]: wouldn't we want some sort of notification to the user, and wouldn't we want to try again until we get it? i don't think we can really do much without the tree loading properly, can we?

**Review by davetsay — CHANGES_REQUESTED** [review]

File: src/persistence/MCWSPersistenceProvider.js (hunk 1 above)
Comment (jvigliotta) [reply src/persistence/MCWSPersistenceProvider.js:34]: I mean, in this case, the network is down, so not much we can do, but I think some sort of retry setup could work? I'll look into it.

**Review by davetsay — CHANGES_REQUESTED** [review]
This looks good, but I just want to make sure you see this before approved.

I thought you said the unknown type check never happens, because the tree loading blocks the creation of the unknown object? If thats the case, maybe we shouldn't be coding for something that will never happen? If it does happen though, should we create an object Type to handle this, or maybe use another comparator such as `object.unresolvedRequest===true` (property name could need work), rather than a string check?

**Review by davetsay — APPROVED** [review]
