### PR TITLE
Fix local storage filtering overriding historical session filtering set by url

### LINKED ISSUE #233: [Links] Session information in links should be respected
**Describe the defect**

Link session information is being ignored.

**Expected behavior**

Links with session information should be filtered by that session when visited.

**Steps To Reproduce**
1. Filter by a session (we'll call it session A)
2. Then create a link
3. Then in the same browser filter a different set of sessions (we'll say, B, C, D)
4. Open a new tab and paste the link created in step 2
5. The new tab is filtered by sessions B, C, and D from step 3, it should be filtered by session A, which is the session when the link was created

**Additional context**

### PR DESCRIPTION
**Pull request by davetsay**
Closes #233

### CODE REVIEW

File: src/historical/HistoricalProvider.js [hunk 1]
```diff
@@ -517,11 +517,11 @@ define([
...
 
         const sessions = this.getSessionService();
-        const session = sessions.getHistoricalSession();
+        const sessionFilter = sessions.getHistoricalSessionFilter();
 
-        if (session) {
-            params.filter.session_id = '(' + session.numbers.join(',') + ')';
-            params.filter.session_host = session.host;
+        if (sessionFilter) {
+            params.filter.session_id = '(' + sessionFilter.numbers.join(',') + ')';
```
Comment (jvigliotta) [inline src/historical/HistoricalProvider.js:523]:
```suggestion
            params.filter.session_id = `(${sessionFilter.numbers.join(',')})`;
```

File: src/multipleHistoricalSessions/sessionSelector/historicalSessionSelector.vue [hunk 2]
```diff
@@ -188,10 +188,10 @@ export default {
             });
         },
         setMarkedSessions() {
-            if(this.activeSessions.numbers && this.activeSessions.host) {
+            if(this.sessionFilter.numbers && this.sessionFilter.host) {
                 this.availableSessions.forEach(session => {
-                    if (this.activeSessions.numbers.some((sessionNumber => sessionNumber == session.number))
-                        && this.activeSessions.host === session.host) {
+                    if (this.sessionFilter.numbers.some((sessionNumber => sessionNumber == session.number))
```
Comment (jvigliotta) [inline src/multipleHistoricalSessions/sessionSelector/historicalSessionSelector.vue:193]:
```suggestion
                    if (this.sessionFilter.numbers.some((sessionNumber => sessionNumber === session.number))
```

**Review by jvigliotta — APPROVED** [review]
Good to go!
