### PR TITLE
Fix Historical provider unit tests

### LINKED ISSUE #129: Update Historical Provider unit tests
Historical Provider unit tests were broken in a previous legacy code update. We need to get back up and running and increase code coverage.

### PR DESCRIPTION
**Pull request by davetsay**
Closes #129

### CODE REVIEW

File: src/historical/HistoricalProviderSpec.js [hunk 1]
```diff
@@ -1,124 +1,113 @@
...
-            mockOpenMct.notifications.alert.and.returnValue(mockNotification);
+        mockSessionService = jasmine.createSpyObj('SessionService', [
+          'getHistoricalSession'
+        ]);
+        spyOn(HistoricalProvider.prototype, 'getSessionService').and.returnValue(mockSessionService);
 
+        mockOpenMct.notifications = jasmine.createSpyObj('notificationAPI', [
+            'alert'
+        ]);
+        mockNotification = jasmine.createSpyObj('notification', [
```
Comment (jvigliotta) [inline src/historical/HistoricalProviderSpec.js:41]: what's this 'on' and 'off'? I don't think we have that on notifications (maybe we did in the past?)

**Review by jvigliotta — APPROVED** [review]
GTG
